<a href="https://colab.research.google.com/github/C0deB3ast/Data_analysis_work/blob/main/Give_me_some_Credit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd

In [25]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [26]:
df = pd.read_csv('/content/drive/MyDrive/Give me some credit/cs-training.csv', na_values=['NA'])

In [27]:
df.head()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Unnamed: 0                            150000 non-null  int64
 1   SeriousDlqin2yrs                      150000 non-null  int64
 2   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 3   age                                   150000 non-null  int64
 4   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 5   DebtRatio                             150000 non-null  float64
 6   MonthlyIncome                         120269 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 8   NumberOfTimes90DaysLate               150000 non-null  int64
 9   NumberRealEstateLoansOrLines          150000 non-null  int64
 10  NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 11  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(8)
memory usage: 13.7 MB

In [29]:
df.describe()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,1.202690e+05,150000.000000,150000.000000,150000.000000,150000.000000,146076.000000
mean,75000.500000,0.066840,6.048438,52.295207,0.421033,353.005076,6.670221e+03,8.452760,0.265973,1.018240,0.240387,0.757222
std,43301.414527,0.249746,249.755371,14.771866,4.192781,2037.818523,1.438467e+04,5.145951,4.169304,1.129771,4.155179,1.115086
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,37500.750000,0.000000,0.029867,41.000000,0.000000,0.175074,3.400000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,75000.500000,0.000000,0.154181,52.000000,0.000000,0.366508,5.400000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,112500.250000,0.000000,0.559046,63.000000,0.000000,0.868254,8.249000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,150000.000000,1.000000,50708.000000,109.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000

In [30]:
df

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
149995,149996,0,0.040674,74,0,0.225131,2100.0,4,0,1,0,0.0
149996,149997,0,0.299745,44,0,0.716562,5584.0,4,0,1,0,2.0
149997,149998,0,0.246044,58,0,3870.000000,NaN,18,0,1,0,0.0
149998,149999,0,0.000000,30,0,0.000000,5716.0,4,0,0,0,0.0
149999,150000,0,0.850283,64,0,0.249908,8158.0,8,0,2,0,0.0

In [31]:
df = df.rename(columns={'Unnamed: 0' : 'Customer_Id'})

In [32]:
median_income = df['MonthlyIncome'].median()
df['MonthlyIncome'] = df['MonthlyIncome'].fillna(median_income)

In [33]:
mode_dependents = df['NumberOfDependents'].mode()[0]
df['NumberOfDependents'] = df['NumberOfDependents'].fillna(mode_dependents)

In [34]:
df.isna().sum()

Customer_Id                             0
SeriousDlqin2yrs                        0
RevolvingUtilizationOfUnsecuredLines    0
age                                     0
NumberOfTime30-59DaysPastDueNotWorse    0
DebtRatio                               0
MonthlyIncome                           0
NumberOfOpenCreditLinesAndLoans         0
NumberOfTimes90DaysLate                 0
NumberRealEstateLoansOrLines            0
NumberOfTime60-89DaysPastDueNotWorse    0
NumberOfDependents                      0
dtype: int64

In [35]:
median_age = df['age'].median()
df.loc[df['age'] == 0, 'age'] = median_age

In [36]:
df[df['NumberOfTimes90DaysLate'] >= 96]

,Customer_Id,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
1733,1734,1,1.0,27,98,0.0,2700.0,0,98,0,98,0.0
2286,2287,0,1.0,22,98,0.0,5400.0,0,98,0,98,0.0
3884,3885,0,1.0,38,98,12.0,5400.0,0,98,0,98,0.0
4417,4418,0,1.0,21,98,0.0,0.0,0,98,0,98,0.0
4705,4706,0,1.0,21,98,0.0,2000.0,0,98,0,98,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
147774,147775,1,1.0,68,98,255.0,5400.0,0,98,0,98,0.0
149153,149154,1,1.0,24,98,54.0,5400.0,0,98,0,98,0.0
149239,149240,0,1.0,26,98,0.0,2000.0,0,98,0,98,0.0
149439,149440,1,1.0,34,98,9.0,5400.0,0,98,0,98,0.0
149769,149770,0,1.0,23,98,0.0,5400.0,0,98,0,98,0.0

In [37]:
df[(df['NumberOfTime30-59DaysPastDueNotWorse'] >= 96) &
   (df['NumberOfTimes90DaysLate'] >= 96) &
   (df['NumberOfTime60-89DaysPastDueNotWorse'] >= 96)].shape

(269, 12)

In [38]:
df = df[~((df['NumberOfTime30-59DaysPastDueNotWorse'] >= 96) &
   (df['NumberOfTimes90DaysLate'] >= 96) &
   (df['NumberOfTime60-89DaysPastDueNotWorse'] >= 96))]

In [39]:
df.shape

(149731, 12)

In [40]:
df[df['RevolvingUtilizationOfUnsecuredLines']>1].shape

(3321, 12)

In [41]:
df['RevolvingUtilizationOfUnsecuredLines'].sort_values(ascending=False).head(20)

85489     50708.0
31414     29110.0
16956     22198.0
149160    22000.0
149279    20514.0
117315    18300.0
21978     17441.0
124533    13930.0
72592     13498.0
71705     13400.0
125718    12369.0
58852     11843.0
83052     11553.0
76726     10821.0
13669     10209.0
123071    10151.0
50695      9684.0
8199       9340.0
60021      9193.0
99651      8831.0
Name: RevolvingUtilizationOfUnsecuredLines, dtype: float64

In [42]:
cap_val= df['RevolvingUtilizationOfUnsecuredLines'].quantile(0.99)
df['RevolvingUtilizationOfUnsecuredLines'] = df['RevolvingUtilizationOfUnsecuredLines'].clip(upper=cap_val)

In [43]:
df['RevolvingUtilizationOfUnsecuredLines'].describe()

count    149731.000000
mean          0.319279
std           0.351296
min           0.000000
25%           0.029771
50%           0.153491
75%           0.555601
max           1.093342
Name: RevolvingUtilizationOfUnsecuredLines, dtype: float64

In [47]:
debt_cap_val = df['DebtRatio'].quantile(0.95)
df['DebtRatio'] = df['DebtRatio'].clip(upper=debt_cap_val)

In [48]:
df['DebtRatio'].describe()

count    149731.000000
mean        255.233174
std         663.442353
min           0.000000
25%           0.175998
50%           0.367119
75%           0.870021
max        2452.000000
Name: DebtRatio, dtype: float64

In [46]:
df[df['DebtRatio'] > 10][['DebtRatio', 'MonthlyIncome']].head(20)

     DebtRatio  MonthlyIncome
6       4983.0         5400.0
8         46.0         5400.0
14       477.0            0.0
16      2058.0         5400.0
32       977.0         5400.0
41        75.0         5400.0
44      1687.5            1.0
50      3095.0            0.0
58      2477.0         5400.0
62      1720.0         5400.0
71      1824.0         5400.0
73      3162.0            0.0
86      3282.0         5400.0
90      4983.0            0.0
92      2662.0         5400.0
100       15.0         5400.0
109     4739.0         5400.0
118      269.0         5400.0
124     4090.0         5400.0
130      994.0         5400.0

In [53]:
df[df['MonthlyIncome'] < 100 ]['DebtRatio'].describe()

count    2268.000000
mean     1006.873185
std       920.289427
min         0.000000
25%        93.000000
50%       754.750000
75%      1865.250000
max      2452.000000
Name: DebtRatio, dtype: float64